'use strict';
let products=[{title:'Наушники',price:2500,category:'Электроника',pop:8},{title:'Футболка',price:1100,category:'Одежда',pop:4},{title:'Чай',price:300,category:'Продукты',pop:6}];let cart={},orders=[],currentUser='';
const $=id=>document.getElementById(id);const money=n=>n.toLocaleString('ru-RU')+' ₽';
function renderProducts(){let items=products.map((p,i)=>({...p,i})).filter(p=>$('category').value==='all'||p.category===$('category').value);if($('sort').value==='price')items.sort((a,b)=>a.price-b.price);if($('sort').value==='popular')items.sort((a,b)=>b.pop-a.pop);if($('sort').value==='new')items.reverse();$('products').replaceChildren();for(const p of items){const card=document.createElement('div');card.className='demo';const title=document.createElement('h3');title.textContent=p.title;const desc=document.createElement('p');desc.textContent=`${p.category} · ${money(p.price)}`;const button=document.createElement('button');button.textContent='Добавить в корзину';button.onclick=()=>{cart[p.i]=(cart[p.i]||0)+1;renderCart()};card.append(title,desc,button);$('products').append(card)}}
function renderCart(){$('cart').replaceChildren();let sum=0;for(const [i,qty] of Object.entries(cart)){let p=products[i];sum+=p.price*qty;let row=document.createElement('p');row.textContent=`${p.title} — ${qty} × ${money(p.price)} `;let minus=document.createElement('button');minus.textContent='−';minus.setAttribute('aria-label',`Уменьшить количество: ${p.title}`);minus.onclick=()=>{cart[i]--;if(!cart[i])delete cart[i];renderCart()};let plus=document.createElement('button');plus.textContent='+';plus.setAttribute('aria-label',`Увеличить количество: ${p.title}`);plus.onclick=()=>{cart[i]++;renderCart()};row.append(minus,plus);$('cart').append(row)}$('total').textContent=`Итого: ${money(sum)}`}
function renderOrders(){if(!$('admin-panel').hidden){$('orders').replaceChildren();for(const order of orders){const p=document.createElement('p');p.textContent=`№${order.id} · ${order.name} · ${money(order.total)} · ${order.status} `;const b=document.createElement('button');b.textContent='Отметить выполненным';b.onclick=()=>{order.status='Выполнен';renderOrders()};p.append(b);$('orders').append(p)}}$('history').textContent=currentUser?orders.filter(o=>o.name===currentUser).map(o=>`Заказ №${o.id}: ${o.status}`).join(' · ')||'Заказов пока нет':''}
$('category').onchange=renderProducts;$('sort').onchange=renderProducts;
$('checkout').onsubmit=e=>{e.preventDefault();let total=Object.entries(cart).reduce((sum,[i,q])=>sum+products[i].price*q,0);if(!total){$('receipt').textContent='Корзина пуста';return}const form=new FormData(e.target);const id=orders.length+1;orders.push({id,name:form.get('name'),total,status:'Принят'});$('receipt').textContent=`Заказ №${id} принят. Оплата: ${form.get('payment')}. Сумма: ${money(total)}. Это учебное подтверждение.`;cart={};renderCart();renderOrders();e.target.reset()};
$('profile').onsubmit=e=>{e.preventDefault();currentUser=new FormData(e.target).get('user');$('profile-result').textContent=`Вы вошли как ${currentUser} (демо без сервера)`;renderOrders()};
$('feedback').onsubmit=e=>{e.preventDefault();$('feedback-result').textContent='Сообщение показано в демо; отправка на сервер не настроена.';e.target.reset()};
$('admin').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);$('admin-panel').hidden=!(f.get('login')==='admin'&&f.get('password')==='admin');if($('admin-panel').hidden)alert('Неверные демонстрационные данные');renderOrders()};
$('add-product').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);products.push({title:f.get('title'),price:Number(f.get('price')),category:f.get('category'),pop:0});renderProducts();e.target.reset()};renderProducts();renderCart();
